### ISSUE TITLE
Add Chaos Mode (Delays, Drops, Corruption)

### ISSUE THREAD

**Issue by Shashwatpandey4** [Shashwatpandey4/DataFlux#11]
Objective:
Inject faults into emitters for resilience testing.

Tasks:

1. Add `chaos.py` with:
 - `simulate_latency()`
 - `simulate_failure()`
 - `simulate_payload_corruption()`

2. Load fault parameters from `chaos.yaml`:

```yaml
latency_ms: 100-500
drop_rate: 0.01
corrupt_rate: 0.005
```

Expected Outcome:
Run with `--chaos chaos.yaml` to simulate random emitter faults.
