### ISSUE TITLE
Add Emitter Behavior Profiles (Bursty, Cyclic, Offline)

### ISSUE THREAD

**Issue by Shashwatpandey4** [Shashwatpandey4/DataFlux#7]
Objective:
Simulate realistic data patterns like bursts, spikes, or sleep cycles.

Tasks:

Create a new folder: `behavior_profiles/`.

Define profile templates (`bursty.yaml`, `9to5_usage.json`, etc.).

Add logic in emitter to load and respect profile rules (e.g., active/inactive intervals).

Example Profile:

```yaml
intervals:
  - start: 09:00
    end: 17:00
    eps: 500
  - start: 17:01
    end: 08:59
    eps: 10
```

Expected Outcome:
`dataflux --profile 9to5_usage.yaml` adjusts emitter rate based on time.
